version: 2.1

executors:
  build-image:
    docker:
      - image: eu.gcr.io/mgcp-infrastructure/toolbox:latest 

commands:
  init_script:
    steps:
      - run:
          name: GCP OIDC auth
          command: |
            echo "${CIRCLE_OIDC_TOKEN}" > /tmp/oidc_access_token
            cat >> /tmp/gcloud-service-key.json \<<- EOF
            {
              "type": "external_account",
              "audience": "//iam.googleapis.com/projects/${WIP_PROJECT_NO}/locations/global/workloadIdentityPools/circleci-oidc/providers/circleci",
              "subject_token_type": "urn:ietf:params:oauth:token-type:jwt",
              "token_url": "https://sts.googleapis.com/v1/token",
              "service_account_impersonation_url": "https://iamcredentials.googleapis.com/v1/projects/-/serviceAccounts/ci-sva@${WIP_PROJECT_ID}.iam.gserviceaccount.com:generateAccessToken",
              "credential_source": {
                "file": "/tmp/oidc_access_token",
                "format": {
                  "type": "text"
                }
              }
            }
            EOF

jobs:
  plan:
    executor: build-image
    steps:
      - checkout
      - init_script
      - run:
          name: Lint
          command: bin/lint.sh
      - run:
          name: Running Terraform Plan
          command: bin/plan.sh
      - persist_to_workspace:
          root: terraform
          paths:
            - terraform-*.tar.gz
            - terraform-*.plan

  apply:
    executor: build-image
    steps:
      - checkout
      - init_script
      - attach_workspace:
          at: /root/project/terraform
      - run:
          name: Applying Terraform Plan
          command: bin/apply.sh

workflows:
  terraform_flow:
    jobs:
      - plan:
          context:
            - gcp-token
      - hold:
          type: approval
          requires:
            - plan
          filters:
            branches:
              ignore: master
      - apply:
          context:
            - gcp-token
          requires:
            - hold
          filters:
            branches:
              ignore: master
